name: Java CI

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
    - run: git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
    - run: git config --global credential.helper store
    - run: git fetch origin
    - run: git checkout workflow-branch
    - run: git status
    - run: git branch
    - run: echo "Hello" > test-reports/hello.txt
    - run: git add test-reports/hello.txt
    - run: git commit -m "Hello"
    - run: git push --set-upstream origin workflow-branch
