name: Java CI/CD Pipeline Example

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
    - name: Create .aws Directory
      run: mkdir ./.aws
    - name: Prepare AWS Access File
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output ./.aws/config aws/awsconfig.gpg
      env:
        GPGPW: ${{secrets.awspassword}}        
    - name: Change config File Permissions
      run: chmod 0600 ./.aws/config
    - name: Prepare AWS Credentials file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output ./.aws/credentials aws/awscredentials.gpg
      env:
        GPGPW: ${{secrets.awspassword}}        
    - name: Change AWS Credentials File Permissions
      run: chmod 0600 ./.aws/credentials
    - name: Prepare pem file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output marx4universe.pem secrets/marx4universe.pem.gpg
      env:
        GPGPW: ${{secrets.awspassword}}        
    - name: Change pem File Permissions
      run: chmod 0400 marx4universe.pem
      
    - name: aws
      run: aws --version
    - name: aws 
      run: aws ec2 describe-instances
