name: Java CI/CD Pipeline Example

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Create .aws Directory
      run: mkdir ./.aws
    - name: Prepare AWS Access File
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output ./.aws/config aws/awsconfig.gpg
      env:
        GPGPW: ${{secrets.awspassword}}        
    - name: Change config File Permissions
      run: chmod 0600 ./.aws/config
    - name: Prepare AWS Credentials file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output ./.aws/credentials aws/awscredentials.gpg
      env:
        GPGPW: ${{secrets.awspassword}}        
    - name: Change AWS Credentials File Permissions
      run: chmod 0600 ./.aws/credentials
   
    - name: Look at config and credentials
      run: cat ./.aws/config
    - run: cat ./.aws/credentials
    - name: Prepare pem file
      run: gpg --quiet --batch --yes --decrypt --passphrase="$GPGPW" --output marx4universe.pem secrets/marx4universe.pem.gpg
      env:
        GPGPW: ${{secrets.awspassword}}        
    - name: Change pem File Permissions
      run: chmod 0400 marx4universe.pem
      
    - name: aws
      run: aws --version
    - name: aws 
      run: aws ec2 describe-instances
      env:
        AWS_SHARED_CREDENTIALS_FILE: ./.aws/credentials
        AWS_CONFIG_FILE: ./.aws/config
    - name: Launch EC2 Instance
      run: aws ec2 run-instances --image-id ami-05c1fa8df71875112 --key-name marx4universe --security-group-ids sg-07c8684f6311ac6dd \
           --subnet-id subnet-9e956ae4 --region=us-east-2 --instance-type=t2.small
      env:
        AWS_SHARED_CREDENTIALS_FILE: ./.aws/credentials
        AWS_CONFIG_FILE: ./.aws/config
